### ISSUE TITLE
Error executing '/usr/bin/vlc'; return code: -1

### ISSUE THREAD

**Issue by probonopd** [darealshinji/vlc-AppImage#1]
```
linux@linux:~> /home/linux/Downloads/VLC-2.2.6.glibc2.16-x86_64.AppImage 
Error: Error executing '/usr/bin/vlc'; return code: -1
```

**Comment by darealshinji** [comment]
Does it immediately exit? No other hints on what went wrong?

**Comment by probonopd** [comment]
Correct. Could be missing permissions, missing files, etc.

**Comment by darealshinji** [comment]
I didn't test VLC in a clean environment so I had no issues, my bad. The problem was apparently the full `/usr/bin/vlc` path in the desktop file. https://github.com/darealshinji/vlc-AppImage/commit/b101c63062099f5ce6a7f66ca6c792ea90ce655d should fix that.

**Comment by probonopd** [comment]
Getting 

```
Your input can't be opened:
VLC is unable to open the MRL 'https://www.youtube.com/watch?v=Le-PVXUCl0M'. Check the log for details.
```

**Comment by darealshinji** [comment]
Enabling GnuTLS in the build should fix it.

**Comment by probonopd** [comment]
Thanks, can you please do so?

**Comment by darealshinji** [comment]
Yes, but I always do a test build on my PC before I push a commit here.

**Comment by darealshinji** [comment]
Playing streams seems to work now. Anything else spotted that's missing?

**Comment by probonopd** [comment]
Getting lots of

```
You attempted to reach www.youtube.com. However the security certificate presented by the server is unknown and could not be authenticated by any trusted Certification Authority. This problem may be caused by a configuration error or an attempt to breach your security or your privacy.

If in doubt, abort now.

This is the certificate presented by www.youtube.com:
subject `C=US,ST=California,L=Mountain View,O=Google Inc,CN=*.google.com', issuer `C=US,O=Google Inc,CN=Google Internet Authority G2', EC key 256 bits, signed using RSA-SHA256, activated `2017-07-25 08:46:44 UTC', expires `2017-10-17 08:28:00 UTC', SHA-1 fingerprint `41876832af24b362b4fc937f3cfe4105bbd119d7'

If in doubt, abort now.

You attempted to reach r4---sn-j5caxn0g4-umae.googlevideo.com. However the security certificate presented by the server is unknown and could not be authenticated by any trusted Certification Authority. This problem may be caused by a configuration error or an attempt to breach your security or your privacy.

If in doubt, abort now.
```

Do you also get these?

**Comment by darealshinji** [comment]
No. Does installing `ca-certificates` help?

**Comment by probonopd** [comment]
I'm on openSUSE and I think they are in a different path here, compared to Ubuntu...

**Comment by darealshinji** [comment]
Try to add the files to the AppImage: https://packages.ubuntu.com/trusty-updates/ca-certificates

If that doesn't work we may need help from someone who knows more about VLC.

**Comment by darealshinji** [comment]
Nevermind, libgnutls seems to look for `/etc/ssl/certs/ca-certificates.crt`, so adding the files shouldn't help. I don't even know if this is something that should be bundled.

**Comment by probonopd** [comment]
Seeing on the command line:

```
[0000000000f350c8] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007fe24407fac8] gnutls tls session error: Certificate verification failure (0x0042)
[00007fe24407fac8] gnutls tls session error:  * Certificate not verified
[00007fe24407fac8] gnutls tls session error:  * Signer not found
[0000000000fe65c8] core playlist: stopping playback
[00007fe23c07bec8] gnutls tls session error: Certificate verification failure (0x0042)
[00007fe23c07bec8] gnutls tls session error:  * Certificate not verified
[00007fe23c07bec8] gnutls tls session error:  * Signer not found
```

We can test where it is looking for certificates:

```
linux@linux:~/Downloads/squashfs-root> strace -f ./AppRun 2>&1 | grep cert
[pid 11157] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY <unfinished ...>
[pid 11163] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY <unfinished ...>
```

Clearly it is not picking up certificates from within the AppImage.

Where certificates go is apparently entirely random by distribution:

https://serverfault.com/questions/62496/ssl-certificate-location-on-unix-linux

**Comment by darealshinji** [comment]
I could try to patch gnutls to look into different directories. But I can't guarantee that I will be successful at it.

**Comment by probonopd** [comment]
That would be awesome. I think this needs to be solved for other AppImages, too...

**Comment by darealshinji** [comment]
I don't know if it really works, but here is a patch I've applied to the gnutls source:
``` diff
--- a/lib/system.c
+++ b/lib/system.c
@@ -389,16 +389,16 @@
 		r += ret;
 #endif
 
-#ifdef DEFAULT_TRUST_STORE_FILE
-	ret =
-	    gnutls_x509_trust_list_add_trust_file(list,
-						  DEFAULT_TRUST_STORE_FILE,
-						  crl_file,
-						  GNUTLS_X509_FMT_PEM,
-						  tl_flags, tl_vflags);
-	if (ret > 0)
-		r += ret;
-#endif
+	ret = gnutls_x509_trust_list_add_trust_file(list, "/etc/ssl/ca-bundle.pem", crl_file, GNUTLS_X509_FMT_PEM, tl_flags, tl_vflags);
+	if (ret > 0) r += ret;
+	ret = gnutls_x509_trust_list_add_trust_file(list, "/etc/ssl/certs/ca-certificates.crt", crl_file, GNUTLS_X509_FMT_PEM, tl_flags, tl_vflags);
+	if (ret > 0) r += ret;
+	ret = gnutls_x509_trust_list_add_trust_file(list, "/etc/pki/tls/cert.pem", crl_file, GNUTLS_X509_FMT_PEM, tl_flags, tl_vflags);
+	if (ret > 0) r += ret;
+	ret = gnutls_x509_trust_list_add_trust_file(list, "/usr/local/share/certs/ca-root-nss.crt", crl_file, GNUTLS_X509_FMT_PEM, tl_flags, tl_vflags);
+	if (ret > 0) r += ret;
+	ret = gnutls_x509_trust_list_add_trust_file(list, "/etc/ssl/cert.pem", crl_file, GNUTLS_X509_FMT_PEM, tl_flags, tl_vflags);
+	if (ret > 0) r += ret;
 
 #ifdef DEFAULT_BLACKLIST_FILE
 	ret = gnutls_x509_trust_list_remove_trust_file(list, DEFAULT_BLACKLIST_FILE, GNUTLS_X509_FMT_PEM);
```

Here's the patched library: [libgnutls.so.28.zip](https://github.com/darealshinji/vlc-AppImage/files/1209168/libgnutls.so.28.zip)

**Comment by probonopd** [comment]
Yes, it works 👍 💯 
Can we get a ppa for this so that we can put it into all AppImages?
Like https://github.com/AppImage/AppImages/blob/c9e6b6b365fcd97e2980c0844c478904c030a25a/recipes/meta/Recipe#L194

**Comment by darealshinji** [comment]
Yes, I can make a PPA. I guess I'll have to make packages for libgnutls26, libgnutls28 and libgnutls30.

**Comment by probonopd** [comment]
Which is [another point](https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues#libgnutls) for my collection of Desktop Linux Platform Issues...

**Comment by darealshinji** [comment]
Here's the PPA: https://launchpad.net/~djcj/+archive/ubuntu/gnutls-patched

This may not be the right place, but anyway, a few notes to the Desktop Linux Platform Issues:

Library filenames:
> The names of libraries should reflect the version as given by upstream.

This is not how library interface versioning is working. The number appended to the library name is increased whenever a non-backward compatible change to the library interface was made. If a new feature was added, but the library is still backwards compatible (can be used by apps built against older versions) only the minor version is bumped. That's also why glibc and libstdc++ are still soversion 6 (something I'm very thankful about). The minor version is not included in the actual soname of the ELF header. The versioning scheme of the actual project usually differs from the library versioning (and many projects also provide multiple libraries). That's why the library x265 version 2.5 doesn't have the soversion 2.5 or 25.

libstdc++.so.6:
> Why is it necessary to still keep adding symbols to it, making software compiled against later versions fail on earlier versions?

Adding support for newer C++ standards (mostly I guess).

HarfBuzz:
> Bundling HarfBuzz seems to cause symbol lookup error: /usr/lib64/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level.

Because of the prefixed "hb_" I'm assuming `hb_buffer_set_cluster_level` is a harfbuzz symbol and should be provided by libharfbuzz.

Image formats:
> Currently every distribution names these differently

I think the different naming in case of tiff, png and jpeg libraries is actually coming from different non-compatible version being available. There's i.e. libjpeg and libjpeg-turbo. The library versioning was a bit weird there in past, so libjpeg.so.62 (meaning 6.2 I think) is actually older than libjpeg.so.8. Or for libpng the soversion refers to the release branch (very uncommon for other libraries). So libpng.so.12 is from PNG 1.2.x, libpng.so.16 is from PNG 1.6.x, etc. I think tiff has a more regular soname versioning and some distros provide libtiff.so.4 along with libtiff.so.5 for backwards compatiblity.

**Comment by probonopd** [comment]
> Here's the PPA: https://launchpad.net/~djcj/+archive/ubuntu/gnutls-patched

You rock... [added](https://github.com/AppImage/AppImages/commit/080f81eeebc445688376992eb622cc725b3b5606) 👍

**Comment by probonopd** [comment]
> This may not be the right place, but anyway, a few notes to the Desktop Linux Platform Issues

I welcome this discussion and have opened an [own issue](https://github.com/AppImage/AppImageKit/issues/445) for it.

**Comment by darealshinji** [comment]
Can we close this? The original issue is solved.

**Comment by probonopd** [comment]
Yes. Thank you very much! 👍

**Comment by asashnov** [comment]
> > Here's the PPA: [https://launchpad.net/~djcj/+archive/ubuntu/gnutls-patched](https://launchpad.net/%7Edjcj/+archive/ubuntu/gnutls-patched)

This PPA is not available now

**Comment by asashnov** [comment]
Dispite PPA has gone, somebody may need GNUTLS patched for searching root CA in different locations. I did it as a Docker image: https://github.com/asashnov/mc-dockers/tree/backport-and-patch-gnutls/gnutls-builder

**Comment by probonopd** [comment]
Here is one more:

```
"/usr/share/ca-certs/.prebuilt-store/"    // Clear Linux OS; https://github.com/knapsu/plex-media-player-appimage/issues/17#issuecomment-437710032
```

**Comment by probonopd** [comment]
@darealshinji what happened to the PPA? I can't find these libs in https://launchpad.net/~djcj/+archive/ubuntu/libcurl-slim, either.
