### ISSUE TITLE
Please add AppStream information

### ISSUE THREAD

**Issue by probonopd** [darealshinji/vlc-AppImage#2]
No AppStream appdata file is present in the AppImage. Please provide one in the AppImage as per the instructions on https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps. This will help the AppImage to be displayed correctly in AppImageHub.

There is one at
http://git.videolan.org/gitweb.cgi/vlc.git/?p=vlc.git;a=blob_plain;f=share/vlc.appdata.xml.in;h=121259500d88fe10ea3a8515aa2952c6dca6ef0a;hb=6112f49ff9ce7abae5370cb61387a83c433fbc19

**Comment by darealshinji** [comment]
Did https://github.com/darealshinji/vlc-AppImage/commit/0686f9c887ed8827c9f8fc1d28c88745b5ff9f08 fix this?

**Comment by probonopd** [comment]
According to @ximion, usr/share/appdata is a legacy path replaced by `usr/share/metainfo`.

**Comment by darealshinji** [comment]
Interesting. But I have no `/usr/share/metainfo` on my Ubuntu 16.04 machine, only `/usr/share/appdata`. Should I still rename it? Or I make a symlink so both paths exist.

**Comment by probonopd** [comment]
Please just rename it, thanks.

**Comment by darealshinji** [comment]
Appdata is now saved in `usr/share/metainfo`.

**Comment by probonopd** [comment]
Thanks, I was able to successfully import it into https://github.com/AppImage/AppImageHub/blob/master/database/VLC/vlc.appdata.xml.
