### ISSUE TITLE
Recording a screencast fails

### ISSUE THREAD

**Issue by probonopd** [darealshinji/vlc-AppImage#3]
When trying to record a screencast as mp4 I get:

>Streaming / Transcoding failed:
It seems your Libav/FFmpeg (libavcodec) installation lacks the following encoder:
H264 - MPEG-4 AVC (part 10).
If you don't know how to fix this, ask for support from your distribution.
>
>This is not an error inside VLC media player.
Do not contact the VideoLAN project about this issue.

Media -> Convert/Save -> Capture Device -> Desktop -> Arrow next to "Convert/Save" button -> Convert -> leave the default profile (first in the dropdown) selected -> enter a destination file -> Start

**Comment by darealshinji** [comment]
Enabling libx264 and perhaps a few other third-party codecs might help. Suggestions are welcome. Should I enable as much as possible or only the most useful ones?

**Comment by probonopd** [comment]
I would say the most common and most useful. Thanks!

**Comment by darealshinji** [comment]
I've enabled x264 and x265. It's only enabled in VLC, if that still doesn't work I'll enable it in ffmpeg too.

**Comment by probonopd** [comment]
Does the recording work for you now? I seem to no more get the errors but no recording either... could well be that the mistake is on my side though.

**Comment by darealshinji** [comment]
Recording desktop works, tested in a clean Ubuntu 14.04 chroot environment. Set the fps to something higher like 30, that might help. I couldn't figure how to record the sound, might as well be an issue with chroot (I prefer simplescreenrecorder for that anyway).

**Comment by probonopd** [comment]
Thank you.
