### ISSUE TITLE
Could you make it integrate into the system?

### ISSUE THREAD

**Issue by Lvaskz** [darealshinji/vlc-AppImage#4]
Hi, this is more a request than a problem, although perhaps for some people it is.
Appimage is not integrated into the linuxmint system 18.2. In some appimages at the time of making the application executable, the application asked if you would like integrate it into the system, but I see that it does not happen now. Nor the official version of krita. Could you make it possible in any way?
When you have many appimage not integrated in the system, it gets some tedious fill the desktop with shortcuts
thanks

**Comment by probonopd** [comment]
Please use the optional `appimaged` daemon which will integrate AppImages into the desktop automatically for you.

https://github.com/AppImage/AppImageKit/blob/appimagetool/master/README.md#appimaged-usage

**Comment by darealshinji** [comment]
A system integration dialog was added.

**Comment by Lvaskz** [comment]
Thanks for that!!!. i noted something, the icon is mising.                                                                                                                                                                                                                                                                                                                                 I attached some images, can you add some one ? 
![cone-audio-large vlc](https://user-images.githubusercontent.com/29207169/29928452-4a463e52-8e26-11e7-94a5-3a6c047644a5.png)
![vlc_icon_svg](https://user-images.githubusercontent.com/29207169/29928454-4a475062-8e26-11e7-9308-36e7fc174d6d.png)

![vlc-media-player-icon-19](https://user-images.githubusercontent.com/29207169/29928453-4a47837a-8e26-11e7-956a-04f7e3d01d8f.png)

**Comment by darealshinji** [comment]
The name specified by the .desktop file is `VLC media player`, so the script is looking for icons with the name `VLCmediaplayer.png` instead of `vlc.png`. This should be easy to fix.

**Comment by Lvaskz** [comment]
thank you
