### ISSUE TITLE
Error during compile: "error: 'x264_bit_depth' undeclared"

### ISSUE THREAD

**Issue by mikerogerz** [darealshinji/vlc-AppImage#6]
CC       video_chroma/libvaapi_x11_plugin_la-copy.lo
  CC       codec/avcodec/libvaapi_x11_plugin_la-vaapi.lo
  CC       codec/libx265_plugin_la-x265.lo
  CC       codec/libx264_plugin_la-x264.lo
  CC       codec/libvpx_plugin_la-vpx.lo
  CC       demux/caf.lo
codec/x264.c: In function 'Open':
codec/x264.c:850:26: error: 'x264_bit_depth' undeclared (first use in this function)
         const int mask = x264_bit_depth > 8 ? X264_CSP_HIGH_DEPTH : 0;
                          ^
codec/x264.c:850:26: note: each undeclared identifier is reported only once for each function it appears in
  CC       codec/avcodec/libavformat_plugin_la-fourcc.lo
Makefile:9088: recipe for target 'codec/libx264_plugin_la-x264.lo' failed
make[4]: *** [codec/libx264_plugin_la-x264.lo] Error 1

**Comment by cmatomic** [comment]
ubuntu 16.04

```
codec/avcodec/hwdummy.c:80:70: warning: unused parameter 'data' [-Wunused-parameter]
 static int Copy(vlc_va_t *va, picture_t *pic, void *opaque, uint8_t *data)
                                                                      ^
  CC       codec/libx265_plugin_la-x265.lo
  CC       codec/libx264_plugin_la-x264.lo
  CC       codec/crystalhd.lo
codec/x264.c: In function 'Open':
codec/x264.c:850:26: error: 'x264_bit_depth' undeclared (first use in this function)
         const int mask = x264_bit_depth > 8 ? X264_CSP_HIGH_DEPTH : 0;
                          ^
codec/x264.c:850:26: note: each undeclared identifier is reported only once for each function it appears in
  CC       demux/caf.lo
Makefile:9088: recipe for target 'codec/libx264_plugin_la-x264.lo' failed
make[4]: *** [codec/libx264_plugin_la-x264.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from codec/crystalhd.c:42:0:
codec/h264_nal.h: In function 'convert_sps_pps':
codec/h264_nal.h:29:9: warning: variable 'i_profile' set but not used [-Wunused-but-set-variable]
     int i_profile;
         ^
codec/crystalhd.c: At top level:
codec/h264_nal.h:107:13: warning: 'convert_h264_to_annexb' defined but not used [-Wunused-function]
 static void convert_h264_to_annexb( uint8_t *p_buf, uint32_t i_len,
             ^
make[4]: Leaving directory '/home/programas/vlc-AppImage/vlc-build/vlc-2.2.8/modules'
Makefile:9654: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/programas/vlc-AppImage/vlc-build/vlc-2.2.8/modules'
Makefile:4528: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/programas/vlc-AppImage/vlc-build/vlc-2.2.8/modules'
Makefile:2265: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/programas/vlc-AppImage/vlc-build/vlc-2.2.8'
Makefile:2150: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by darealshinji** [comment]
I will investigate it.

**Comment by cmatomic** [comment]
I was able to resolve to continue compiling the h.264 codec, making the following modifications
line 141
```
# x264
if [ ! -e ./usr/lib/libx264.so ]; then
  cd x264
  ./configure --prefix="$PREFIX" --enable-shared --disable-cli --enable-strip
  make clean
  make -j$JOBS V=0
  make install
  cd -
fi
```

```
# x264
if [ ! -e ./usr/lib/libx264.so ]; then
  cd x264
  ./configure --prefix="$PREFIX" 
  make clean
  make -j$JOBS V=0
  make install
  cd -
fi
```

**Comment by darealshinji** [comment]
The cause of this was a change in x264's source code. `x264_bit_depth` is no longer declared. I've added a patch that will automatically be applied.

**Comment by mikerogerz** [comment]
Fix worked great, thanks a lot.

**Comment by sekatt** [comment]
> I was able to resolve to continue compiling the h.264 codec, making the following modifications
> line 141 on build script
> 
> ```
> # x264
> if [ ! -e ./usr/lib/libx264.so ]; then
>   cd x264
>   ./configure --prefix="$PREFIX" --enable-shared --disable-cli --enable-strip
>   make clean
>   make -j$JOBS V=0
>   make install
>   cd -
> fi
> ```
> ```
> # x264
> if [ ! -e ./usr/lib/libx264.so ]; then
>   cd x264
>   ./configure --prefix="$PREFIX" 
>   make clean
>   make -j$JOBS V=0
>   make install
>   cd -
> fi
> ```

can u tell me where exactly it is : in Makefile in vlc2.2.6 folder??
thx
