### ISSUE TITLE
support for appimaged

### ISSUE THREAD

**Issue by Lvaskz** [darealshinji/vlc-AppImage#7]
hi, i am using linuxmint 18.03, 64 bits, cinnamon. Actually i installed the appimage daemon called appimaged.
This is appimaged "appimaged is an optional daemon that watches locations like ~/bin and ~/Downloads for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc. It also unregisters AppImages again from the system if they are deleted. If firejail is installed, it runs the AppImages with it."https://github.com/AppImage/AppImageKit
Many appimages, using this can register the icon in the system menu without installing, only putting the appimages on the bin folder or download folder, etc but many appimages icons are not recognized by appimaged, like rambox, vlc, nextcloud etc.
By that reason i request if this is posible, vlc can be supported by appimaged

**Comment by probonopd** [comment]
Actually it _should_ be working.

On my system:

```
me@host:~$ find /home/me/ | grep VLC
/home/me/Downloads/VLC-2.2.8.glibc2.16-x86_64.AppImage

me@host:~$ grep -r VLC-2.2.8.glibc2.16 /home/me/.local/share/applications/
/home/me/.local/share/applications/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d-vlc.desktop

cat /home/me/.local/share/applications/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d-vlc.desktop

cat /home/me/.local/share/applications/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d-vlc.desktop | grep Icon
Icon=appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc

me@host:~$ find /home/ | grep appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc
/home/me/.local/share/icons/hicolor/256x256/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.png
/home/me/.local/share/icons/hicolor/16x16/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.xpm
/home/me/.local/share/icons/hicolor/16x16/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.png
/home/me/.local/share/icons/hicolor/48x48/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.png
/home/me/.local/share/icons/hicolor/48x48/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc-xmas.png
/home/me/.local/share/icons/hicolor/32x32/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.xpm
/home/me/.local/share/icons/hicolor/32x32/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.png
/home/me/.local/share/icons/hicolor/32x32/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc-xmas.xpm
/home/me/.local/share/icons/hicolor/128x128/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc.png
/home/me/.local/share/icons/hicolor/128x128/apps/appimagekit_b02a3bb0424cf0e74c46ba0b230f562d_vlc-xmas.png
```

But indeed the icon does not show up immediately. Why?

(I don't think this is an issue of the AppImage, at least I could not find anything this AppImage is doing wrong.)

**Comment by Lvaskz** [comment]
well, it seems work

**Comment by probonopd** [comment]
Maybe the same as here? https://github.com/nomad-desktop/nx-software-center/issues/13#issuecomment-359188554

**Comment by Lvaskz** [comment]
It is a curious thing that the AppImage that give problems are of type 1. Of course with some exceptions like synfig.
Talking about this issue, have you some advance  to fix it in the near futuro? I think that AppImaged is real usefull, I would like that linuxmint can adoptitby default or all of that distros, but well.

**Comment by probonopd** [comment]
> well, it seems work

Now you are confusing me:

> Talking about this issue, have you some advance to fix it in the near futuro? 

Is if working or not?

**Comment by Lvaskz** [comment]
Sorry, it is working. 😁

**Comment by darealshinji** [comment]
So, should I close this?
