### ISSUE TITLE
3.0.0 is released

### ISSUE THREAD

**Issue by probonopd** [darealshinji/vlc-AppImage#8]
3.0.0 is released, please upgrade the AppImage. Thanks.

**Comment by darealshinji** [comment]
I'm getting segfaults with vlc-cache-gen and after a little workaround to make the AppImage build anyway it will only launch the VLC cli interface and no gui.
Here's the latest build script I used: https://gist.github.com/darealshinji/0502dad100b78f7a3374ed83b0fa443b

**Comment by probonopd** [comment]
Looks like someone has succeeded building an AppImage here:
https://github.com/anupam-git/vlc-appimage/releases

But the AppImage has some issues that you have solved long time ago. Maybe the two of you can collaborate?

**Comment by kuboosoft** [comment]
I can help, exist documentation for convert rpms? because I can kill two birds with it...
