### ISSUE TITLE
Fails to load libgiognutls.so

### ISSUE THREAD

**Issue by probonopd** [darealshinji/vlc-AppImage#9]
> Unfortunately the VLC AppImage package was not able to run on my system. It showed the following error message on startup:
> 
> Failed to load module: /usr/lib64/gio/modules/libgiognutls.so

Source: https://verummeum.com/blog/2018/10/14/portable-package-formats/

**Comment by ald0n** [comment]
Works just fine here on gentoo with *glib-networking* package installed.

**Comment by probonopd** [comment]
Question is, is the `glib-networking` package (or its equivalent) installed automatically in the default installation on all relevant distributions?
